### ISSUE TITLE
Multi-line arrays / Trailing commas in (multi-line) arrays

### ISSUE THREAD

**Issue by TimWolla** [php-fig/per-coding-style#14]
PHP supports trailing commas in arrays since 7.2. As of now the existing formatting standards of PHP-FIG do not specify whether or not (or when) trailing commas in Arrays are acceptable or required. More generally the formatting of multi-line arrays is left unspecified, whereas for other constructs it is clearly specified how they need to be split across multiple lines.

This is related to #3, since PHP 7.3+ introduces additional constructs where trailing commas are allowed and PHP 8.0 introduces named parameters which are syntactically very close to an associative array literal.

**Comment by Crell** [comment]
I know at least some coding standards mandate the trailing comma if multi-lining an array.

If we do something here, it should apply to all multi-line-with-comma situations.  Eg, function calls, function definitions, arrays, etc.

**Comment by samdark** [comment]
There are objective advantages always having a comma:

1. It allows you to move lines around in multi-line arrays w/o tracking commas.
2. Diff is better in case of appending lines in multi-line arrays.

**Comment by TimWolla** [comment]
Possible PR: #18

**Comment by KorvinSzanto** [comment]
Yep #18 merged and specifies when a trailing comma must or must not be used so I think this is settled.
