### ISSUE TITLE
Add example of a nowdoc/heredoc as a function parameter 

### ISSUE THREAD

**Issue by TimWolla** [php-fig/per-coding-style#30]
I believe the indentation requirement of nowdoc/heredoc is not obviously correct within a multi-line function parameter list, as the ending delimiter also needs to be indented compared to e.g. an anonymous function.

```php
<?php

// Right?
var_dump(
    'foo',
    <<<'EOT'
        Line 1
        Line 2
        Line 3
        EOT,
    'bar',
);

// Wrong?
var_dump(
    'foo',
    <<<'EOT'
    Line 1
    Line 2
    Line 3
    EOT,
    'bar',
);
```

see https://3v4l.org/eGlGY
see #5

**Comment by KorvinSzanto** [comment]
I'd argue that:
> Instead, the heredoc MUST be indented once past the indentation of the scope it's declared in.

makes it clear that your first example is allowed and your second example is disallowed.

**Comment by TimWolla** [comment]
I don't think it's *clear*, otherwise I wouldn't have opened this issue. Especially since a function call does not open a new scope if using common terminology (in PHP it's even arguable if `if` opens a new scope). Also the nowdoc/heredoc section is the only section where the term “scope” appears.

Certainly another explicit example can't hurt?

**Comment by TimWolla** [comment]
Alternatively this could be rephrased entirely:

"The heredoc body and ending delimiter must be indented one additional level compared to the opening delimiter"

**Comment by KorvinSzanto** [comment]
"Scope" here refers to the indentation scope, not the variable scope. I wouldn't mind adding another example if you want to open a PR.
