### ISSUE TITLE
Spaces in type casting

### ISSUE THREAD

**Issue by dmotitsk** [php-fig/per-coding-style#35]
Are there any requirements regarding spaces in type casting? There is the requirement:

Type casting operators MUST NOT have any space within the parentheses

But what about the space between the type and the expression? I.e.

$intValue = (int) $input;

or 

$intValue = (int)$input;

**Comment by samdark** [comment]
Currently there's no requirement for it.

**Comment by guvra** [comment]
The `!` operator is also not specified.

**Comment by vjik** [comment]
Maybe create this requirement?

`(int) $input`  looks good.

**Comment by samdark** [comment]
@Crell, @KorvinSzanto thoughts?

**Comment by Crell** [comment]
I've only ever seen it without a space: `(int)$x`.

**Comment by guvra** [comment]
> I've only ever seen it without a space: (int)$x.

It's the default value in [php-cs-fixer](https://cs.symfony.com/doc/rules/cast_notation/cast_spaces.html).
Both laravel and symfony use a space.

**Comment by KorvinSzanto** [comment]
PSR-12, Laminas, and the PHP docs all also add spaces. I can't really think of a good reason to omit this so I'd be okay with adding this for typecasts. Something like 

> Typecasts MUST be separated from the variable they are operating on by exactly one space.

**Comment by Crell** [comment]
If that's the de facto consensus, I don't have a strong argument to not follow it on this one.  Sounds like we need a PR.
