### ISSUE TITLE
Clarifying blank line between methods

### ISSUE THREAD

**Issue by mbniebergall** [php-fig/per-coding-style#54]
I've read and re-read the specs, and had a peer search as well, and I am not finding clarity that there MUST be a blank line _between_ class methods. All the examples show it, but it doesn't seem to be clear that it is required in the spec.

For example, this seems to be allowed:

```
class BlankLine
{
    public function firstMethod()
    {
        ...
    }
    public function nextMethod()
    {
        ...
    }
}
```

When it _should_ be this instead:

```
class BlankLine
{
    public function firstMethod()
    {
        ...
    }

    public function nextMethod()
    {
        ...
    }
}
```

Can anyone prove me wrong in the spec? If not, I'll get a PR open to clarify this.

**Comment by KorvinSzanto** [comment]
We currently allow both of your examples and I don't think we want to change that. The blank lines between methods can be added as part of:
> Blank lines MAY be added to improve readability and to indicate related blocks of code except where explicitly forbidden.
