### ISSUE TITLE
планы

### ISSUE THREAD

**Issue by i-coder** [php-fig/per-coding-style#6]
на русском не планируете? Спасибо

**Comment by Jean85** [comment]
Write in English please.

Roughly translated:

> do you plan to speak Russian? Thanks 

No, sorry. We need to use a language that is understood by the widest possible audience.

**Comment by i-coder** [comment]
look at the map and the size of Russia, are there few people? I think the audience will only double

**Comment by vdelau** [comment]
The main working language of the FIG is English and the official output of the FIG is in English. Within the FIG there is currently no bandwidth to provide and maintain translations into other languages, even though there are a lot of people in the FIG having a primary language other than English.

If someone would contribute translations of specifications into other languages than English, we could look into making those available through official FIG means. However, the official and thus normative specifications and other artefacts like source code will be in English.

One other aspect to keep in mind for translations is that such a process would most likely require peer review by other individuals who are fluent in the respective language.

**Comment by Jean85** [comment]
> If someone would contribute translations of specifications into other languages than English, we could look into making those available through official FIG means. However, the official and thus normative specifications and other artefacts like source code will be in English.
> 
> One other aspect to keep in mind for translations is that such a process would most likely require peer review by other individuals who are fluent in the respective language.

And those are in fact the reasons why we tried multiple times to support translations in the past but it failed: https://github.com/php-fig/fig-standards/pulls?q=translation

Conveying the same exact meaning of a standard through a translated text is really hard, and it opens to all kinds of misconceptions and wrong interpretations. Thus, we have to stick to a single language, and even use a standardized language format (see the [RFC 2119](http://tools.ietf.org/html/rfc2119) references on top of nearly all PSRs).
