### ISSUE TITLE
4.2 Traits need empty lines between blocks

### ISSUE THREAD

**Issue by Nex-Otaku** [php-fig/per-coding-style#60]
![image](https://user-images.githubusercontent.com/2260071/218672460-04a0e0c1-3df7-4ff9-87a4-909570ff77ce.png)

See Steven Mcconnell "Code Complete", page 729, chapter 31 "Layout and Style".

Blocks (multiline statements) must be delimited with a blank line.

So instead of

```php
<?php

class Talker
{
    use A;
    use B {
        A::smallTalk insteadof B;
    }
    use C {
        B::bigTalk insteadof C;
        C::mediumTalk as FooBar;
    }
}
```

you get

```php
<?php

class Talker
{
    use A;

    use B {
        A::smallTalk insteadof B;
    }

    use C {
        B::bigTalk insteadof C;
        C::mediumTalk as FooBar;
    }
}
```

It's more readable and keeps consistent rythm throughout all text.

**Comment by KorvinSzanto** [comment]
Are you saying we should have blank lines between all multiline statements in general? We currently allow that:

> Blank lines MAY be added to improve readability and to indicate related blocks of code except where explicitly forbidden.

I don't think it makes sense to add blank lines between multiline statements as a requirement at this point because it would require changes to a ton of code in the wild with limited improvements to readability.

**Comment by Nex-Otaku** [comment]
@KorvinSzanto yes but it's exactly for changes in existing code and impovements to readability this project does exist, doesn't it?

Anyway we can insert blank lines in trait example even without adding a rule about blank lines.

When people will start adjusting their style guides to match PER then they will look not only at explicit rules but for sure they will look at the code examples.

So it will encourage to use blank lines around multiline blocks not forbidding to do otherwise.

**Comment by KorvinSzanto** [comment]
I'd accept a pull request that adds blank lines to the given example if that's all you're after but I don't think we want to require blank lines today.
