### ISSUE TITLE
Please add the version number to the specs

### ISSUE THREAD

**Issue by jefhar** [php-fig/per-coding-style#70]
Unless you are specifically looking at the URL of the page, you don't know what PER version the specifications are. The version should be placed near the top of the document, above the fold.

This allows mere mortals to glance at the document to see the version. Without it, there is no way to ascertain that the page contains the same version as another page. The images contain two different pages that may or may not have the same information, but there is no way to tell which is the most current version.

<img width="807" alt="Screen Shot 2023-04-06 at 11 58 12 AM" src="https://user-images.githubusercontent.com/22824070/230433539-d0f08be0-804b-4bc5-aa20-3389866c2216.png">
<img width="807" alt="Screen Shot 2023-04-06 at 11 58 54 AM" src="https://user-images.githubusercontent.com/22824070/230433669-b4ed9717-5545-4322-8354-28b0adcf8cfb.png">

**Comment by Jean85** [comment]
Solved in https://github.com/php-fig/www.php-fig.org/pull/317/commits/7275758882e9fba0e36b46c15e58e7b4e15f9ac3, deploy incoming!
