### ISSUE TITLE
Deprecated attribute

### ISSUE THREAD

**Issue by Crell** [php-fig/per-coding-style#96]
PHP now has a `#[Deprecated]` attribute.  As PER-CS, do we care and are there any guidelines we should put around it, or it is out of scope?  (Out of scope is fully acceptable, I just want to be explicit about it.)

**Comment by Crell** [comment]
The only thing I can think of for us to try and standardize is wording for the deprecation message.  I don't know if it's too early for that, though.

**Comment by TimWolla** [comment]
https://github.com/php/php-src/pull/14750 might be of interest regarding samples of wording used in PHP itself.

**Comment by samdark** [comment]
The placement of attributes is the scope of the coding style but the message itself... I don't think so.

**Comment by Crell** [comment]
I will mark this as closed with no action needed in ~3 days unless someone from the WG objects.

**Comment by KorvinSzanto** [comment]
I agree this should be closed without changes but I do think there might be opportunity to add some "SHOULD"s around using attributes to specify metadata in general when available. I wonder if we  could recommend people use the `Deprecated` attribute and others like `Override` without being too specific about what to use when.

Maybe something like:

> Attributable constructs such as classes, methods, properties, class constants, functions, parameters, etc. SHOULD include relevant descriptive attributes where available and necessary. For example, if a method is considered "deprecated" by the codebase, a `\Deprecated` or equivalent attribute `SHOULD` be used to specify.


But that might be too general

**Comment by Crell** [comment]
No action required.
